Maven
ep6-TH-Bingen/project_alpha_omega pull request #14
Opened 2017-08-01 13:56 UTC by EdenTewelde

Created a maven project with a HelloWorld class. It builds a self-contained jar.

2017-08-01 14:26 UTC, nipafx requested changes
Looks great: good, clean POM without any obvious problems. I can't try it out right now, though, so you'll have to wait until later tonight for a thumbs-up.

I was about to point out the whole "Closes #7" stuff but you figured it out. :smiley:

2017-08-01 14:26 UTC, nicolaiparlog commented on target/maven-archiver/pom.properties
> +#Generated by Maven
Please remove the `target` folder from the PR.

2017-08-01 15:55 UTC, EdenTewelde commented
I saw your comment in the other PR, so I changed it here 😄

2017-08-01 18:51 UTC, nipafx requested changes
A few changes and this can be merged.

2017-08-01 18:51 UTC, nicolaiparlog commented on pom.xml
> +	<version>1.0</version>
During development, you should add `-SNAPSHOT` here. ([Why?](https://stackoverflow.com/a/5901460/2525313))

2017-08-01 18:51 UTC, nicolaiparlog commented on pom.xml
> +		<dependency>
Please remove the JUnit dependency - it is not needed for #7 and should be added in #12.

2017-08-01 18:51 UTC, nicolaiparlog commented on pom.xml
> +					<execution>
This block is only needed for testing.

2017-08-02 08:56 UTC, Domm2501 commented
Seeing that the changes you requested were made, is it now eligible to merge?

2017-08-02 08:59 UTC, nicolaiparlog commented
Yes.

2017-08-02 09:57 UTC, merged